version: '3.3'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5432:5432"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dash-app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=your_db_name
      - DB_USER=your_user
      - DB_PASS=your_password

